// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDwcEYp1P3Dw8ea_FmR8AvSxUz6k1wmZU',
    appId: '1:186941997391:android:ad107546857d411763853a',
    messagingSenderId: '186941997391',
    projectId: 'collegesapiens',
    databaseURL:
        'https://collegesapiens-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'collegesapiens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4nuGFxY2-WdbWO7umv4fCzfMVTE5m8Vs',
    appId: '1:186941997391:ios:53f25851ab79a73563853a',
    messagingSenderId: '186941997391',
    projectId: 'collegesapiens',
    databaseURL:
        'https://collegesapiens-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'collegesapiens.firebasestorage.app',
    iosClientId:
        '186941997391-gtkj2ju7f2l3e2rkmalvtveug5bnbt5q.apps.googleusercontent.com',
    iosBundleId: 'com.collegesapien.app',
  );
}
