name: Markdown Links

on:
  push:
  pull_request:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --no-progress
            --exclude-mail
            --accept 200,204,429
            README.md
            CONTRIBUTING.md
            CODE_OF_CONDUCT.md
            SECURITY.md
            admin/README.md
            server/README.md
            app/README.md
            app/QUICKSTART.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
